### ISSUE TITLE
Divulgación

### ISSUE THREAD

**Issue by mariacamilarg** [PythonBootcampUniandes/pythonbootcampuniandes.github.io#2]
Mandar poster + link a pagina a conocidos en diferentes lugares. 

En universidades:

- Uniandes:
- Nacional: Carlos
- Tadeo: Carlos

En MeetUp:

- Conocido: Carlos

**Comment by forero** [comment]
acabo de crear este archivo para que sepamos quien esta encargado de que
https://github.com/PythonBootcampUniandes/pythonbootcampuniandes.github.io/blob/master/divulgacion.md
