### ISSUE TITLE
Hacer poster

### ISSUE THREAD

**Issue by mariacamilarg** [PythonBootcampUniandes/pythonbootcampuniandes.github.io#3]
Logos por ahora: python, uniandes, spyder

**Comment by mariacamilarg** [comment]
una imagen así me parecería chevere:

https://geekswipe.net/wp-content/uploads/2014/10/Geekswipe-Python-Twitter-bot-Source-Photo-by-Karthikeyan-KC.jpg

**Comment by forero** [comment]
también me gusta ese estilo de imagen

**Comment by ccordoba12** [comment]
@PythonBootcampUniandes/core, acabo de crear un nuevo repo para el poster:

https://github.com/PythonBootcampUniandes/poster

El texto está en [Lyx](http://www.lyx.org/), porque es el que programa que yo utilizo para crear todo lo que hago en Latex. Espero que no les moleste ;-)

En el repo también está la versión en PDF del poster para que le den una ojeada rapida y me cuenten que les parece.

Si quieren hacerle cambios, la idea sería que instalaran Lyx, hicieran los cambios a `poster.lyx` y crearan una PR con los mismos. Los archivos `.lyx` son de texto plano y bastante legibles.

En Ubuntu sólo es necesario hacer

    sudo apt-get install lyx
    sudo apt-get install texlive-lang-spanish

para poder editar el archivo y generar el PDF.

----

*Nota*: Me hace falta poner el logo de Uniandes. Para no olvidarlo, cree PythonBootcampUniandes/poster#1
