### ISSUE TITLE
encuesta de opinion final

### ISSUE THREAD

**Issue by forero** [PythonBootcampUniandes/pythonbootcampuniandes.github.io#9]
armar una encuesta para conocer la opinion final de los asistentes: lo bueno, lo malo y lo feo.

**Comment by steff456** [comment]
La idea es que respondan la encuesta por computador o a mano?

**Comment by forero** [comment]
Lo mas facil es que sea un formulario de google para que los respondan por computador.

**Comment by steff456** [comment]
Hola! La encuesta la dejamos anónima, o que pongan el nombre y su correo?

**Comment by ccordoba12** [comment]
@steff456, anónima me parece lo mejor, así la gente podrá expresar más libremente sus opiniones.

Pero lo hablamos mañana en el curso.

**Comment by steff456** [comment]
Yo mañana no puedo acompañarlos, pero ya está el preview hecho para que lo revisen y cualquier cosa me avisen. 
https://docs.google.com/forms/d/e/1FAIpQLSf0G600I95n29ZvfM66KHyDJEAl-cC5Xt1aYndpF9GlZoSyXg/viewform

**Comment by steff456** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSf0G600I95n29ZvfM66KHyDJEAl-cC5Xt1aYndpF9GlZoSyXg/viewform?usp=sf_link
